### ISSUE TITLE
Unable to connect to a GKE cluster from the local machine

### ISSUE THREAD

**Issue by irajhedayati** [hagay3/skuber#342]
I created a cluster in GKE. Then, I tried to run an application locally to connect to the cluster, and it failed. The in-cluster method works fine.

here is the error:

```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at skuber.api.Configuration$.valueAt$1(Configuration.scala:118)
	at skuber.api.Configuration$.authProviderRead$1(Configuration.scala:180)
	at skuber.api.Configuration$.toK8SAuthInfo$1(Configuration.scala:189)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$9(Configuration.scala:209)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$6(Configuration.scala:154)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.convert.JavaCollectionWrappers$JListWrapper.map(JavaCollectionWrappers.scala:138)
	at skuber.api.Configuration$.topLevelYamlToK8SConfigMap$1(Configuration.scala:154)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$1(Configuration.scala:209)
	at scala.util.Try$.apply(Try.scala:210)
	at skuber.api.Configuration$.parseKubeconfigStream(Configuration.scala:104)
	at skuber.api.Configuration$.$anonfun$parseKubeconfigFile$2(Configuration.scala:95)
	at scala.util.Success.flatMap(Try.scala:258)
	at skuber.api.Configuration$.parseKubeconfigFile(Configuration.scala:94)
	at skuber.api.Configuration$.$anonfun$defaultK8sConfig$3(Configuration.scala:308)
	at scala.util.Failure.orElse(Try.scala:221)
	at skuber.api.Configuration$.$anonfun$defaultK8sConfig$2(Configuration.scala:308)
	at scala.Option.getOrElse(Option.scala:201)
	at skuber.api.Configuration$.defaultK8sConfig(Configuration.scala:307)
	at skuber.api.client.package$.defaultK8sConfig(package.scala:218)
	at skuber.api.client.package$.init(package.scala:193)
	at skuber.package$.k8sInit(package.scala:288)
```

**To Reproduce**

1. create a cluster
  ```bash
  $PROJECT=dataedu
  $CLUSTER_NAME
  gcloud auth application-default login --project=$PROJECT
  gcloud config set project $PROJECT
  gcloud container clusters create $CLUSTER_NAME --project=$PROJECT
  export USE_GKE_GCLOUD_AUTH_PLUGIN=True
  gcloud container clusters get-credentials $CLUSTER_NAME --zone=us-central1-a --project=$PROJECT
  ```
2. connect to cluster
```scala
  implicit val system: ActorSystem = ActorSystem()
  implicit val dispatcher: ExecutionContextExecutor = system.dispatcher
 
 val k8s = k8sInit
```

**Expected behavior**
Be able to connect to GKE cluster from local machine same as in-cluster

**skuber version**
`2.6.7`

**kubernetes server version**
```
❯ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.7-gke.500
```

**Cloud Platform**
GCP

**Additional context**

When it tries to create the client, it's looking for the following structure:

```
- name: 
  user:
    auth-provider:
      config:
        access-token: 
        cmd-args: 
        cmd-path: 
        expiry: 
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

but in the new versions, `gcloud` doesn't support it and has the following format:

```
- name: 
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env:
      installHint: 
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

So, either I'm having an issue in configuration or the new authentication method is not supported in **skuber**.

**Comment by hagay3** [comment]
Hi @irajhedayati  ,
Thank you for taking the time and creating an issue :)

skuber not supporting yet exec config:
https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#ExecConfig

I'll look into that to provide a solution

**Comment by hagay3** [comment]
@irajhedayati 
v4.0.1 released along with the [support for exec config](https://github.com/hagay3/skuber/pull/347)
https://github.com/hagay3/skuber/releases/tag/v4.0.1

**Comment by irajhedayati** [comment]
Thank you @hagay3   this feature will really speedup the dev process. Appreciate the prompt action
