### ISSUE TITLE
too old resource version

### ISSUE THREAD

**Issue by brycechesternewman** [hagay3/skuber#93]
Using 2.7.3 watchContinuously(...) throws this exception.

```
Restarting stream due to failure [1]: skuber.api.client.package$K8SException: Status(v1,Status,ListMeta(,,None),Some(Failure),Some(too old resource version: 762700013 (762702363)),Some(Expired),None,Some(410))
skuber.api.client.package$K8SException: Status(v1,Status,ListMeta(,,None),Some(Failure),Some(too old resource version: 762700013 (762702363)),Some(Expired),None,Some(410))
	at skuber.api.watch.BytesToWatchEventSource$.$anonfun$apply$1(BytesToWatchEventSource.scala:22)
	at akka.stream.impl.fusing.Map$$anon$1.onPush(Ops.scala:52)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
	at akka.actor.ActorCell.invoke(ActorCell.scala:548)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Using 2.6.x we don't see this issue. We don't see a reason why this K8SException is being thrown. We are not using Job or Pod TTL and we only delete the job/pod after the watchContinuously returns success or failure. It appears there might be a race condition in as to when Skuber creates the job and associates the resourceVersion. It appears the watch is for some reasons seeing any older version of the resource when it should not.

Here is the job.

```
...
    val job = Job(_jobId).withTemplate(templateSpec)
      .withActiveDeadlineSeconds(activeDeadlineSeconds)
      .withCompletions(1)
      .withParallelism(1)
      .withBackoffLimit(backOffLimit)
```

Here is the watch.
```
...
val stream: (UniqueKillSwitch, Future[Done]) = RestartSource.withBackoff(
      restartSettings.withMaxRestarts(3, 30.seconds))(
      () => _kubernetesClient.watchContinuously[Job](_jobId))
      .viaMat(KillSwitches.single)(Keep.right)
      .toMat(podPhaseMonitor)(Keep.both)
      .run()
...
```

**Comment by brycechesternewman** [comment]
It would appear this code changed and now looks for an error and throws K8SException. Is Status(v1,Status,ListMeta(,,None),Some(Failure),Some(too old resource version: 762700013 (762702363)),Some(Expired),None,Some(410) really considered an error a cause for a K8SException to be thrown?

```
 def watchEventWrapperReads[T <: ObjectResource](implicit objreads: Reads[T]) : Reads[WatchEventWrapper[T]] = (
      (JsPath \ "type").formatEnum(EventType).flatMap { eventType =>
        if (eventType == EventType.ERROR)
          (JsPath \ "object").read[Status].map(status => Left(status))
        else
          (JsPath \ "object").read[T].map(obj => Right(WatchEvent[T](eventType, obj)))
      }
    )```

**Comment by hagay3** [comment]
@brycechesternewman 
Thanks for reporting on the issue, I will try to reproduce that and find a solution.
Can you provide a full code example with the watch invocation?
```
val stream: (UniqueKillSwitch, Future[Done]) = RestartSource.withBackoff(
      restartSettings.withMaxRestarts(3, 30.seconds))(
      () => _kubernetesClient.watchContinuously[Job](_jobId))
      .viaMat(KillSwitches.single)(Keep.right)
      .toMat(podPhaseMonitor)(Keep.both)
      .run()

**Comment by brycechesternewman** [comment]
I am going to close this. The behavior of the K8SException being thrown was unexpected in 2.7.x. I have since modified my code to handle the K8SException. The K8SException with a http status of 410 was being returned when the Kube Job was being rescheduled by Kubernetes. I think the current behavior is fine, but I assume others may run into this now that a K8SException is thrown.
